version: "3.9"

services:

  sonarqube:
    build:
      context: ./sonarqube
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
      - "9000:9000"

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"