version: "3.9"

services:

  sonarqube:
    build:
      context: ./sonarqube
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
      - "9000:9000"

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    environment:
      - JENKINS_OPTS="--httpPort=8585"
    ports:
      - "8585:8585"
      - "50000:50000"
  
  zap:
    image: owasp/zap2docker-bare:2.10.0
    command: zap.sh -daemon -port 8989 -host 0.0.0.0 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true -config scanner.strength=INSANE
    ports:
      - "8989:8989"